<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="3.0" xmlns:ns0="http://hl7.org/fhir">
    <xsl:output method="xml" indent="yes"/>
    <xsl:template match="/">
        <Account xmlns="http://hl7.org/fhir">
            <identifier>
                <use>
                    <xsl:attribute name="id">
                        <xsl:value-of select="/ns0:Account/ns0:identifier/ns0:use/@id"/>
                    </xsl:attribute>
                    <xsl:attribute name="value">
                        <xsl:value-of select="/ns0:Account/ns0:identifier/ns0:use/@value"/>
                    </xsl:attribute>
                    <extension>
                        <xsl:attribute name="url">
                            <xsl:value-of select="/ns0:Account/ns0:identifier/ns0:use/ns0:extension"/>
                        </xsl:attribute>
                        <valueBase64Binary>
                            <xsl:attribute name="value">
                                <xsl:value-of select="/ns0:Account/ns0:identifier/ns0:use/ns0:extension/ns0:valueBase64Binary/@value"/>
                            </xsl:attribute>
                            <xsl:attribute name="id">
                                <xsl:value-of select="/ns0:Account/ns0:identifier/ns0:use/ns0:extension/ns0:valueBase64Binary/@id"/>
                            </xsl:attribute>
                            <extension>
                                <xsl:attribute name="url">
                                    <xsl:value-of select="/ns0:Account/ns0:identifier/ns0:use/ns0:extension/ns0:valueBase64Binary/ns0:extension/@url"/>
                                </xsl:attribute>
                            </extension>
                        </valueBase64Binary>
                        <valueBoolean>
                            <xsl:attribute name="id">
                                <xsl:value-of select="/ns0:Account/ns0:identifier/ns0:use/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/@id"/>
                            </xsl:attribute>
                            <xsl:attribute name="value">
                                <xsl:value-of select="/ns0:Account/ns0:identifier/ns0:use/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/@value"/>
                            </xsl:attribute>
                        </valueBoolean>
                    </extension>
                </use>
            </identifier>
            <status>
                <xsl:attribute name="id">
                    <xsl:value-of select="/ns0:Account/ns0:status/@id"/>
                </xsl:attribute>
                <xsl:attribute name="value">
                    <xsl:value-of select="/ns0:Account/ns0:status/@value"/>
                </xsl:attribute>
                <extension>
                    <xsl:attribute name="url">
                        <xsl:value-of select="/ns0:Account/ns0:status/ns0:extension/@url"/>
                    </xsl:attribute>
                    <valueBase64Binary>
                        <xsl:attribute name="value">
                            <xsl:value-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/@value"/>
                        </xsl:attribute>
                        <xsl:attribute name="id">
                            <xsl:value-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/@id"/>
                        </xsl:attribute>
                        <extension>
                            <xsl:attribute name="url">
                                <xsl:value-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/@url"/>
                            </xsl:attribute>
                            <valueBase64Binary>
                                <xsl:attribute name="value">
                                    <xsl:value-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/@value"/>
                                </xsl:attribute>
                                <xsl:attribute name="id">
                                    <xsl:value-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/@id"/>
                                </xsl:attribute>
                                <extension>
                                    <xsl:attribute name="id">
                                        <xsl:value-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/@id"/>
                                    </xsl:attribute>
                                    <xsl:attribute name="url">
                                        <xsl:value-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/@url"/>
                                    </xsl:attribute>
                                    <valueBase64Binary>
                                        <xsl:attribute name="value">
                                            <xsl:value-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/@value"/>
                                        </xsl:attribute>
                                        <xsl:attribute name="id">
                                            <xsl:value-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/@id"/>
                                        </xsl:attribute>
                                        <extension>
                                            <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension"/>
                                        </extension>
                                    </valueBase64Binary>
                                    <valueBoolean>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean"/>
                                    </valueBoolean>
                                    <valueCanonical>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueCanonical"/>
                                    </valueCanonical>
                                    <valueCode>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueCode"/>
                                    </valueCode>
                                    <valueDate>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueDate"/>
                                    </valueDate>
                                    <valueDateTime>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueDateTime"/>
                                    </valueDateTime>
                                    <valueDecimal>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueDecimal"/>
                                    </valueDecimal>
                                    <valueId>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueId"/>
                                    </valueId>
                                    <valueInstant>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueInstant"/>
                                    </valueInstant>
                                    <valueInteger>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueInteger"/>
                                    </valueInteger>
                                    <valueInteger64>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueInteger64"/>
                                    </valueInteger64>
                                    <valueMarkdown>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueMarkdown"/>
                                    </valueMarkdown>
                                    <valueOid>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueOid"/>
                                    </valueOid>
                                    <valuePositiveInt>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valuePositiveInt"/>
                                    </valuePositiveInt>
                                    <valueString>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueString"/>
                                    </valueString>
                                    <valueTime>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueTime"/>
                                    </valueTime>
                                    <valueUnsignedInt>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueUnsignedInt"/>
                                    </valueUnsignedInt>
                                    <valueUri>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueUri"/>
                                    </valueUri>
                                    <valueUrl>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueUrl"/>
                                    </valueUrl>
                                    <valueUuid>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueUuid"/>
                                    </valueUuid>
                                    <valueAddress>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueAddress"/>
                                    </valueAddress>
                                    <valueAge>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueAge"/>
                                    </valueAge>
                                    <valueAnnotation>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueAnnotation"/>
                                    </valueAnnotation>
                                    <valueAttachment>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueAttachment"/>
                                    </valueAttachment>
                                    <valueCodeableConcept>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueCodeableConcept"/>
                                    </valueCodeableConcept>
                                    <valueCodeableReference>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueCodeableReference"/>
                                    </valueCodeableReference>
                                    <valueCoding>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueCoding"/>
                                    </valueCoding>
                                    <valueContactPoint>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueContactPoint"/>
                                    </valueContactPoint>
                                    <valueCount>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueCount"/>
                                    </valueCount>
                                    <valueDistance>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueDistance"/>
                                    </valueDistance>
                                    <valueDuration>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueDuration"/>
                                    </valueDuration>
                                    <valueHumanName>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueHumanName"/>
                                    </valueHumanName>
                                    <valueIdentifier>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueIdentifier"/>
                                    </valueIdentifier>
                                    <valueMoney>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueMoney"/>
                                    </valueMoney>
                                    <valuePeriod>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valuePeriod"/>
                                    </valuePeriod>
                                    <valueQuantity>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueQuantity"/>
                                    </valueQuantity>
                                    <valueRange>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueRange"/>
                                    </valueRange>
                                    <valueRatio>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueRatio"/>
                                    </valueRatio>
                                    <valueRatioRange>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueRatioRange"/>
                                    </valueRatioRange>
                                    <valueReference>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueReference"/>
                                    </valueReference>
                                    <valueSampledData>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueSampledData"/>
                                    </valueSampledData>
                                    <valueSignature>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueSignature"/>
                                    </valueSignature>
                                    <valueTiming>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueTiming"/>
                                    </valueTiming>
                                    <valueContactDetail>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueContactDetail"/>
                                    </valueContactDetail>
                                    <valueDataRequirement>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueDataRequirement"/>
                                    </valueDataRequirement>
                                    <valueExpression>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueExpression"/>
                                    </valueExpression>
                                    <valueParameterDefinition>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueParameterDefinition"/>
                                    </valueParameterDefinition>
                                    <valueRelatedArtifact>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueRelatedArtifact"/>
                                    </valueRelatedArtifact>
                                    <valueTriggerDefinition>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueTriggerDefinition"/>
                                    </valueTriggerDefinition>
                                    <valueUsageContext>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueUsageContext"/>
                                    </valueUsageContext>
                                    <valueAvailability>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueAvailability"/>
                                    </valueAvailability>
                                    <valueExtendedContactDetail>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueExtendedContactDetail"/>
                                    </valueExtendedContactDetail>
                                    <valueDosage>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueDosage"/>
                                    </valueDosage>
                                    <valueMeta>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueMeta"/>
                                    </valueMeta>
                                    <extension>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:extension"/>
                                    </extension>
                                </extension>
                            </valueBase64Binary>
                            <valueBoolean>
                                <xsl:attribute name="value">
                                    <xsl:value-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/@value"/>
                                </xsl:attribute>
                                <xsl:attribute name="id">
                                    <xsl:value-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/@id"/>
                                </xsl:attribute>
                                <extension>
                                    <xsl:attribute name="url">
                                        <xsl:value-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/@url"/>
                                    </xsl:attribute>
                                    <xsl:attribute name="id">
                                        <xsl:value-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/@id"/>
                                    </xsl:attribute>
                                    <valueBase64Binary>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueBase64Binary"/>
                                    </valueBase64Binary>
                                    <valueBoolean>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueBoolean"/>
                                    </valueBoolean>
                                    <valueCanonical>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueCanonical"/>
                                    </valueCanonical>
                                    <valueCode>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueCode"/>
                                    </valueCode>
                                    <valueDate>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueDate"/>
                                    </valueDate>
                                    <valueDateTime>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueDateTime"/>
                                    </valueDateTime>
                                    <valueDecimal>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueDecimal"/>
                                    </valueDecimal>
                                    <valueId>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueId"/>
                                    </valueId>
                                    <valueInstant>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueInstant"/>
                                    </valueInstant>
                                    <valueInteger>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueInteger"/>
                                    </valueInteger>
                                    <valueInteger64>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueInteger64"/>
                                    </valueInteger64>
                                    <valueMarkdown>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueMarkdown"/>
                                    </valueMarkdown>
                                    <valueOid>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueOid"/>
                                    </valueOid>
                                    <valuePositiveInt>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valuePositiveInt"/>
                                    </valuePositiveInt>
                                    <valueString>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueString"/>
                                    </valueString>
                                    <valueTime>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueTime"/>
                                    </valueTime>
                                    <valueUnsignedInt>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueUnsignedInt"/>
                                    </valueUnsignedInt>
                                    <valueUri>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueUri"/>
                                    </valueUri>
                                    <valueUrl>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueUrl"/>
                                    </valueUrl>
                                    <valueUuid>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueUuid"/>
                                    </valueUuid>
                                    <valueAddress>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueAddress"/>
                                    </valueAddress>
                                    <valueAge>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueAge"/>
                                    </valueAge>
                                    <valueAnnotation>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueAnnotation"/>
                                    </valueAnnotation>
                                    <valueAttachment>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueAttachment"/>
                                    </valueAttachment>
                                    <valueCodeableConcept>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueCodeableConcept"/>
                                    </valueCodeableConcept>
                                    <valueCodeableReference>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueCodeableReference"/>
                                    </valueCodeableReference>
                                    <valueCoding>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueCoding"/>
                                    </valueCoding>
                                    <valueContactPoint>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueContactPoint"/>
                                    </valueContactPoint>
                                    <valueCount>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueCount"/>
                                    </valueCount>
                                    <valueDistance>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueDistance"/>
                                    </valueDistance>
                                    <valueDuration>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueDuration"/>
                                    </valueDuration>
                                    <valueHumanName>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueHumanName"/>
                                    </valueHumanName>
                                    <valueIdentifier>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueIdentifier"/>
                                    </valueIdentifier>
                                    <valueMoney>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueMoney"/>
                                    </valueMoney>
                                    <valuePeriod>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valuePeriod"/>
                                    </valuePeriod>
                                    <valueQuantity>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueQuantity"/>
                                    </valueQuantity>
                                    <valueRange>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueRange"/>
                                    </valueRange>
                                    <valueRatio>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueRatio"/>
                                    </valueRatio>
                                    <valueRatioRange>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueRatioRange"/>
                                    </valueRatioRange>
                                    <valueReference>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueReference"/>
                                    </valueReference>
                                    <valueSampledData>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueSampledData"/>
                                    </valueSampledData>
                                    <valueSignature>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueSignature"/>
                                    </valueSignature>
                                    <valueTiming>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueTiming"/>
                                    </valueTiming>
                                    <valueContactDetail>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueContactDetail"/>
                                    </valueContactDetail>
                                    <valueDataRequirement>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueDataRequirement"/>
                                    </valueDataRequirement>
                                    <valueExpression>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueExpression"/>
                                    </valueExpression>
                                    <valueParameterDefinition>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueParameterDefinition"/>
                                    </valueParameterDefinition>
                                    <valueRelatedArtifact>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueRelatedArtifact"/>
                                    </valueRelatedArtifact>
                                    <valueTriggerDefinition>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueTriggerDefinition"/>
                                    </valueTriggerDefinition>
                                    <valueUsageContext>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueUsageContext"/>
                                    </valueUsageContext>
                                    <valueAvailability>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueAvailability"/>
                                    </valueAvailability>
                                    <valueExtendedContactDetail>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueExtendedContactDetail"/>
                                    </valueExtendedContactDetail>
                                    <valueDosage>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueDosage"/>
                                    </valueDosage>
                                    <valueMeta>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:valueMeta"/>
                                    </valueMeta>
                                    <extension>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueBoolean/ns0:extension/ns0:extension"/>
                                    </extension>
                                </extension>
                            </valueBoolean>
                            <valueCanonical>
                                <xsl:attribute name="id">
                                    <xsl:value-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueCanonical/@id"/>
                                </xsl:attribute>
                                <xsl:attribute name="value">
                                    <xsl:value-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueCanonical/@value"/>
                                </xsl:attribute>
                                <extension>
                                    <xsl:attribute name="url">
                                        <xsl:value-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueCanonical/ns0:extension/@url"/>
                                    </xsl:attribute>
                                    <valueBase64Binary>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueCanonical/ns0:extension/ns0:valueBase64Binary"/>
                                    </valueBase64Binary>
                                    <valueBoolean>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueCanonical/ns0:extension/ns0:valueBoolean"/>
                                    </valueBoolean>
                                    <valueCanonical>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueCanonical/ns0:extension/ns0:valueCanonical"/>
                                    </valueCanonical>
                                    <valueCode>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueCanonical/ns0:extension/ns0:valueCode"/>
                                    </valueCode>
                                    <valueDate>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueCanonical/ns0:extension/ns0:valueDate"/>
                                    </valueDate>
                                    <valueDateTime>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueCanonical/ns0:extension/ns0:valueDateTime"/>
                                    </valueDateTime>
                                    <valueDecimal>
                                        <xsl:copy-of select="/ns0:Account/ns0:status/ns0:extension/ns0:valueBase64Binary/ns0:extension/ns0:valueCanonical/ns0:extension/ns0:valueDecimal"/>
                                    </valueDecimal>
                                </extension>
                            </valueCanonical>
                        </extension>
                    </valueBase64Binary>
                </extension>
            </status>
        </Account>
    </xsl:template>
</xsl:stylesheet>